# Generated by Django 4.0.5 on 2022-06-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(blank=True, max_length=10000, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
                ('sample', models.BooleanField(blank=True, null=True)),
                ('folder', models.IntegerField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
