# Generated by Django 4.0.5 on 2022-06-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
