# Generated by Django 4.0.5 on 2022-06-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='folder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='md5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(default='safe', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='width',
            field=models.IntegerField(),
        ),
    ]
