version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    volumes:
      - .:/code
      - ./secret.txt:/code/secret.txt
      - ${ACTUAL_STORAGE_PATH}:${BOORU_STORAGE_PATH}
      - ${ACTUAL_STATIC_PATH}:${STATIC_ROOT}
    environment:
      # Database
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - LOAD_FIXTURES=${LOAD_FIXTURES}
      - DB_MIGRATE=${DB_MIGRATE}
      - ROLL_SECRET=${ROLL_SECRET}

      # Debugging
      - BOORU_SHOW_FFMPEG_OUTPUT=${BOORU_SHOW_FFMPEG_OUTPUT}
      - DEBUG=${DEBUG}

      # Unit Testing
      - UNIT_TEST=${UNIT_TEST}
      - UNIT_TEST_DISPLAY_COVERAGE=${UNIT_TEST_DISPLAY_COVERAGE}

      # Booru
      - BOORU_STORAGE_PATH=${BOORU_STORAGE_PATH}
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${ACTUAL_STORAGE_PATH}:/storage/
      - ${ACTUAL_STATIC_PATH}:/static/
      - ./.nginx:/etc/nginx/conf.d/booru.conf
    depends_on:
      - web