version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      # Database
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - LOAD_FIXTURES=${LOAD_FIXTURES}
      - DB_MIGRATE=${DB_MIGRATE}

      # Debugging
      - BOORU_SHOW_FFMPEG_OUTPUT=${BOORU_SHOW_FFMPEG_OUTPUT}
      - DEBUG=${DEBUG}

      # Unit Testing
      - UNIT_TEST=${UNIT_TEST}
      - UNIT_TEST_DISPLAY_COVERAGE=${UNIT_TEST_DISPLAY_COVERAGE}
    depends_on:
      - db

