version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=booru
      - POSTGRES_USER=homebooru
      - POSTGRES_PASSWORD=H0meboOru!420
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=booru
      - POSTGRES_USER=homebooru
      - POSTGRES_PASSWORD=H0meboOru!420
      - DEBUG=True
    depends_on:
      - db

