on: [push]

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build -d"