name: Python Unit Tests CI

on: [push]

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
      - uses: actions/checkout@v3
      - name: "Build docker-compose stack"
        run: |
          cd .debug
          docker-compose up -d --build
      - name: "Attach to test container"
        run: docker container attach debug_web_1