on: [push]

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
      - uses: actions/checkout@v3
      - name: "Build docker-compose stack"
        run: docker-compose up -d --build
      - name: "Attach to test container"
        run: docker container attach homebooru-rewritten_web_1